const { type } = require("@testing-library/user-event/dist/type");

const BankCards = () => [
    {
        ID: 1,
        name: "Visa Classic",
        type: "Sayohat uchun",
        currencies: ["USD", "EUR"],
        price: "bepul",
        description: "Karta dizayni",
        features: "Komissiya yo\'q",
        description2: "Hamkorbank terminallari orqali naqd pul yechib olish, o‘tkazish va to‘lovlarni amalga oshirish",
        features2: 'Tez tarjimalar',
        description3: "Biz uni bir daqiqa ichida yuboramiz",
        image: "https://hamkorbank.uz/assets/images-cache/products/physical/visa-exchange/visa_preview.37fe5755.webP",
        BtnCards: false,
    },
    {
        ID: 2,
        name: "HUMO",
        type: "xarid qilish uchun",
        currencies: "so\'m miqdorida mablag\' ajratildi",
        price: "3 kundan boshlab",
        description: "Ishlab chiqish",
        features: "Bepul",
        description2: "Onlayn karta uchun ariza bering",
        features2: "Komissiya yo'q",
        description3: "Arizada 5 million so‘mgacha pul o‘tkazmalari",
        image: "https://hamkorbank.uz/assets/images-cache/products/humo/humo_preview.37fe5755.webP",
        BtnCards: true,
    },
    {
        ID: 3,
        name: "UZCARD",
        type: "Xarid qilish uchun",
        currencies: "so‘m miqdorida mablag‘ ajratildi",
        price: "30 000 so\'m",
        description: "Karta dizayni",
        features: "Bepul",
        description2: "Kartaga texnik xizmat ko'rsatish",
        features2: "komissiya yo'\q",
        description3: "Oʻzbekiston boʻylab toʻlov",
        image: "https://hamkorbank.uz/assets/images-cache/products/physical/uzcard/uzcard_preview.37fe5755.webP",
        BtnCards: true,
    },
    {
        ID: 4,
        name: "Visa Classic",
        type: "Sayohat uchun",
        currencies: ["USD", "EUR"],
        price: "bepul",
        description: "Karta dizayni",
        features: "Komissiya yo\'q",
        description2: "Hamkorbank terminallari orqali naqd pul yechib olish, o‘tkazish va to‘lovlarni amalga oshirish",
        features2: 'Tez tarjimalar',
        description3: "Biz uni bir daqiqa ichida yuboramiz",
        image: "https://hamkorbank.uz/assets/images-cache/products/physical/uzcard-unionpay/uzcard_unionpay_preview.37fe5755.webP",
        BtnCards: true,
    },
    {
        ID: 5,
        name: "Visa Classic",
        type: "Sayohat uchun",
        currencies: ["USD", "EUR"],
        price: "bepul",
        description: "Karta dizayni",
        features: "Komissiya yo\'q",
        description2: "Hamkorbank terminallari orqali naqd pul yechib olish, o‘tkazish va to‘lovlarni amalga oshirish",
        features2: 'Tez tarjimalar',
        description3: "Biz uni bir daqiqa ichida yuboramiz",
        image: "https://hamkorbank.uz/assets/images-cache/products/physical/humo-visa/humo_visa_preview.37fe5755.webP",
        BtnCards: true,
    },
    {
        ID: 6,
        name: "Visa Classic",
        type: "Sayohat uchun",
        currencies: ["USD", "EUR"],
        price: "bepul",
        description: "Karta dizayni",
        features: "Komissiya yo\'q",
        description2: "Hamkorbank terminallari orqali naqd pul yechib olish, o‘tkazish va to‘lovlarni amalga oshirish",
        features2: 'Tez tarjimalar',
        description3: "Biz uni bir daqiqa ichida yuboramiz",
        image: "https://hamkorbank.uz/assets/images-cache/products/physical/unionpay/unionpay_preview.37fe5755.webP",
        BtnCards: false,
    },
    {
        ID: 7,
        name: "Visa Classic",
        type: "Sayohat uchun",
        currencies: ["USD", "EUR"],
        price: "bepul",
        description: "Karta dizayni",
        features: "Komissiya yo\'q",
        description2: "Hamkorbank terminallari orqali naqd pul yechib olish, o‘tkazish va to‘lovlarni amalga oshirish",
        features2: 'Tez tarjimalar',
        description3: "Biz uni bir daqiqa ichida yuboramiz",
        image: "https://hamkorbank.uz/assets/images-cache/products/physical/visa-platinum/visa_platinum_preview.37fe5755.webP",
        BtnCards: true,
    },
    {
        ID: 8,
        name: "Visa Classic",
        type: "Sayohat uchun",
        currencies: ["USD", "EUR"],
        price: "bepul",
        description: "Karta dizayni",
        features: "Komissiya yo\'q",
        description2: "Hamkorbank terminallari orqali naqd pul yechib olish, o‘tkazish va to‘lovlarni amalga oshirish",
        features2: 'Tez tarjimalar',
        description3: "Biz uni bir daqiqa ichida yuboramiz",
        image: "https://hamkorbank.uz/assets/images-cache/products/physical/visa-infinite/visa_infinite_preview.37fe5755.webP",
        BtnCards: true,
    },
    {
        ID: 9,
        name: "Visa Classic",
        type: "Sayohat uchun",
        currencies: ["USD", "EUR"],
        price: "bepul",
        description: "Karta dizayni",
        features: "Komissiya yo\'q",
        description2: "Hamkorbank terminallari orqali naqd pul yechib olish, o‘tkazish va to‘lovlarni amalga oshirish",
        features2: 'Tez tarjimalar',
        description3: "Biz uni bir daqiqa ichida yuboramiz",
        image: "https://hamkorbank.uz/assets/images-cache/products/physical/visa-virtual/visa_virtual_preview.37fe5755.webP",
        BtnCards: true,
    },
]